
#ifndef RANUNCULUS_ENVIRONMENT_HPP
#define RANUNCULUS_ENVIRONMENT_HPP

#define RANUNCULUS_COMPILER_IS_GCC(...) 0
#define RANUNCULUS_COMPILER_IS_CLANG(...) 0
#define RANUNCULUS_COMPILER_IS_MSVC(...) 0

#define RANUNCULUS_COMPILER_IS(COMPILER, ...) RANUNCULUS_COMPILER_IS_ ## COMPILER (__VA_ARGS__)

#ifdef __GNUC__
#undef RANUNCULUS_COMPILER_IS_GCC
#define RANUNCULUS_COMPILER_IS_GCC(...) (__GNUC__ __VA_ARGS__)
#endif

#ifdef _MSC_VER
#undef RANUNCULUS_COMPILER_IS_MSVC
#define RANUNCULUS_COMPILER_IS_MSVC(...) (_MSC_VER __VA_ARGS__)
#endif

#ifdef __clang__
#undef RANUNCULUS_COMPILER_IS_CLANG
#define RANUNCULUS_COMPILER_IS_CLANG(...) (__clang_major__ __VA_ARGS__)
#endif

#endif

